#!/usr/bin/env python3
"""bin2c.py <in.bin> <out.c> <symbol> — embed a binary as a C byte array.

Used by the H4 SDL build to embed the built .res blob (the same yoda.res the WIN32 link
consumes) into the native binary; microfx/src/res/mfxres.cpp parses it at runtime.
"""
import sys

def main():
    inp, out, sym = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(inp, 'rb').read()
    with open(out, 'w') as f:
        f.write("/* generated by tools/bin2c.py from %s — do not edit */\n" % inp.split('/')[-1])
        f.write("const unsigned char %s[] = {\n" % sym)
        for i in range(0, len(data), 16):
            f.write("  " + ",".join("0x%02x" % b for b in data[i:i+16]) + ",\n")
        f.write("};\n")
        f.write("const unsigned int %s_size = %du;\n" % (sym, len(data)))

if __name__ == '__main__':
    main()
