#!/usr/bin/env python3
"""fon2c.py <file.fon> <out.c> — extract raw FNT strikes from a .FON (NE) into C arrays.

Emits one `const unsigned char g_mfxFnt<pixh>[]` per requested strike (default: the 13px
and 16px MS Sans Serif strikes the game maps to via CreateFont(-8)/(-14)). The FNT blocks
are embedded VERBATIM — microfx/src/gdi (mfxtext) parses the v2 FNT header/char table at
runtime. Regenerate with:
  python3 tools/fon2c.py <path-to-SSERIFE.FON> microfx/src/gdi/mfxfont_data.c
"""
import sys, struct
sys.path.insert(0, __file__.rsplit('/', 1)[0])
import reslib

WANTED_PIXH = (13, 16)

def main():
    fon, out = sys.argv[1], sys.argv[2]
    res = reslib.ne_resources(fon)
    strikes = {}
    for (t, n), d in sorted(res.items()):
        if t != 8:                       # RT_FONT
            continue
        pixh, = struct.unpack_from('<H', d, 0x58)
        if pixh in WANTED_PIXH and pixh not in strikes:
            strikes[pixh] = d
    missing = [h for h in WANTED_PIXH if h not in strikes]
    assert not missing, f"strikes not found: {missing}"
    with open(out, 'w') as f:
        f.write("/* generated by tools/fon2c.py — raw FNT strikes (MS Sans Serif bitmap font,\n"
                " * extracted from a Windows SSERIFE.FON). Parsed at runtime by mfxgdi.cpp's\n"
                " * text renderer. Regenerate: python3 tools/fon2c.py <SSERIFE.FON> <this file> */\n")
        for pixh in WANTED_PIXH:
            d = strikes[pixh]
            f.write("const unsigned char g_mfxFnt%d[] = {\n" % pixh)
            for i in range(0, len(d), 16):
                f.write("  " + ",".join("0x%02x" % b for b in d[i:i+16]) + ",\n")
            f.write("};\n")
            f.write("const unsigned int g_mfxFnt%d_size = %du;\n" % (pixh, len(d)))
    print("wrote %s (%s)" % (out, ", ".join("%dpx=%dB" % (h, len(strikes[h])) for h in WANTED_PIXH)))

if __name__ == '__main__':
    main()
